### ISSUE TITLE
compatibility issue with mobile site

### ISSUE THREAD

**Issue by karasawa-user** [kepstin/Fix-pixiv-thumbnails#4]
Thanks for creating this script... it work flawlessly on desktop, but there's issue when it used on mobile version where it make some illustration detached from its place and either cover the description part or sink into background like what my screenshots shown
![Screenshot_20201101-000428](https://user-images.githubusercontent.com/58468168/97785232-5ea8bc80-1bd6-11eb-9a9d-5f7ab3cd8d30.png)
![Screenshot_20201101-000532](https://user-images.githubusercontent.com/58468168/97785241-67998e00-1bd6-11eb-9758-c57a7480e39c.png)

**Comment by kepstin** [comment]
Hi,

Please confirm what browser and userscript extension are you using?

**Comment by kepstin** [comment]
I have reproduced the issue using firefox developer tools. I will see what I can do… the mobile page is very different from the desktop page.

**Comment by kepstin** [comment]
I have put an updated copy of the script in the [develop branch](https://github.com/kepstin/Fix-pixiv-thumbnails/blob/develop/Fix-pixiv-thumbnails.user.js) which should fix the layout issues on mobile.

I am currently verifying compatibility on both the mobile & desktop website. I would appreciate if you can test as well.

**Comment by kepstin** [comment]
I have released version [20201031.3](https://github.com/kepstin/Fix-pixiv-thumbnails/releases/tag/20201031.3) with the fix for this problem. Please let me know if you see any other issues!

Fixed page display (Firefox 82 desktop, using developer tools mobile simulation):
![Screenshot_2020-10-31 The Idolmaster Cinderella Girls, The Idolmaster, honda mio ちゃんみお - pixiv](https://user-images.githubusercontent.com/38788/97790076-0a80e680-1b9c-11eb-941a-d71cdf0a37ce.png)
